<?php

namespace Database\Seeders;

use App\Models\Industry;
use Illuminate\Database\Seeder;

class IndustrySeeder extends Seeder
{
    public function run(): void
    {
        $industries = $this->getIndustries();
        foreach ($industries as $industry) {
            Industry::updateOrCreate(
                ['id' => $industry['id']],
                [
                    'title' => [
                        'en' => $industry['title_en'],
                        'ru' => $industry['title_ru'],
                        'uz_Latn' => $industry['title_uz'],
                    ],
                    'description' => [
                        'en' => $industry['description_en'],
                        'ru' => $industry['description_ru'],
                        'uz_Latn' => $industry['description_uz'],
                    ],
                ]
            );
        }
    }

    private function getIndustries(): array
    {
        return [
            [
                'id' => 1,
                'title_en' => 'Artificial Intelligence',
                'title_ru' => 'Искусственный интеллект',
                'title_uz' => 'Sun’iy intellekt',
                'description_en' => 'Startups in the field of artificial intelligence.',
                'description_ru' => 'Стартапы в области искусственного интеллекта.',
                'description_uz' => 'Sun’iy intellekt sohasidagi startaplar.',
            ],
            [
                'id' => 2,
                'title_en' => 'Blockchain',
                'title_ru' => 'Блокчейн',
                'title_uz' => 'Blokcheyn',
                'description_en' => 'Startups in blockchain technologies.',
                'description_ru' => 'Стартапы в области технологий блокчейн.',
                'description_uz' => 'Blokcheyn texnologiyalari bo‘yicha startaplar.',
            ],
            [
                'id' => 3,
                'title_en' => 'FinTech',
                'title_ru' => 'Финансовые технологии',
                'title_uz' => 'FinTech',
                'description_en' => 'Startups in financial technologies (FinTech).',
                'description_ru' => 'Стартапы в области финансовых технологий (FinTech).',
                'description_uz' => 'Moliyaviy texnologiyalar (FinTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 4,
                'title_en' => 'HealthTech',
                'title_ru' => 'Медицинские технологии',
                'title_uz' => 'HealthTech',
                'description_en' => 'Startups in health technologies (HealthTech).',
                'description_ru' => 'Стартапы в области медицинских технологий (HealthTech).',
                'description_uz' => 'Sog‘liqni saqlash texnologiyalari (HealthTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 5,
                'title_en' => 'EdTech',
                'title_ru' => 'Образовательные технологии',
                'title_uz' => 'EdTech',
                'description_en' => 'Startups in education technologies (EdTech).',
                'description_ru' => 'Стартапы в области образовательных технологий (EdTech).',
                'description_uz' => 'Ta’lim texnologiyalari (EdTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 6,
                'title_en' => 'AgriTech',
                'title_ru' => 'Сельскохозяйственные технологии',
                'title_uz' => 'AgriTech',
                'description_en' => 'Startups in agriculture technologies (AgriTech).',
                'description_ru' => 'Стартапы в области сельскохозяйственных технологий (AgriTech).',
                'description_uz' => 'Qishloq xo‘jaligi texnologiyalari (AgriTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 7,
                'title_en' => 'CleanTech',
                'title_ru' => 'Чистые технологии',
                'title_uz' => 'CleanTech',
                'description_en' => 'Startups in clean technologies (CleanTech).',
                'description_ru' => 'Стартапы в области чистых технологий (CleanTech).',
                'description_uz' => 'Toza texnologiyalar (CleanTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 8,
                'title_en' => 'BioTech',
                'title_ru' => 'Биотехнологии',
                'title_uz' => 'BioTech',
                'description_en' => 'Startups in biotechnology (BioTech).',
                'description_ru' => 'Стартапы в области биотехнологий (BioTech).',
                'description_uz' => 'Biotexnologiyalar (BioTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 9,
                'title_en' => 'Cybersecurity',
                'title_ru' => 'Кибербезопасность',
                'title_uz' => 'Kiberxavfsizlik',
                'description_en' => 'Startups in cybersecurity.',
                'description_ru' => 'Стартапы в области кибербезопасности.',
                'description_uz' => 'Kiberxavfsizlik bo‘yicha startaplar.',
            ],
            [
                'id' => 10,
                'title_en' => 'E-commerce',
                'title_ru' => 'Электронная коммерция',
                'title_uz' => 'E-commerce',
                'description_en' => 'Startups in e-commerce technologies.',
                'description_ru' => 'Стартапы в области электронной коммерции.',
                'description_uz' => 'Elektron savdo (E-commerce) bo‘yicha startaplar.',
            ],
            [
                'id' => 11,
                'title_en' => 'FoodTech',
                'title_ru' => 'Пищевые технологии',
                'title_uz' => 'FoodTech',
                'description_en' => 'Startups in food technologies (FoodTech).',
                'description_ru' => 'Стартапы в области пищевых технологий (FoodTech).',
                'description_uz' => 'Oziq-ovqat texnologiyalari (FoodTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 12,
                'title_en' => 'Gaming',
                'title_ru' => 'Игры и видеоигры',
                'title_uz' => 'Gaming',
                'description_en' => 'Startups in gaming and video games.',
                'description_ru' => 'Стартапы в области игр и видеоигр.',
                'description_uz' => 'O‘yinlar va videoo‘yinlar sohasidagi startaplar.',
            ],
            [
                'id' => 13,
                'title_en' => 'SaaS (Software as a Service)',
                'title_ru' => 'SaaS (Программное обеспечение как услуга)',
                'title_uz' => 'SaaS (Dasturiy ta’minot)',
                'description_en' => 'Startups in Software as a Service (SaaS).',
                'description_ru' => 'Стартапы в области программного обеспечения как услуги (SaaS).',
                'description_uz' => 'SaaS (Software as a Service) bo‘yicha startaplar.',
            ],
            [
                'id' => 14,
                'title_en' => 'TravelTech',
                'title_ru' => 'Технологии путешествий',
                'title_uz' => 'TravelTech',
                'description_en' => 'Startups in travel technologies (TravelTech).',
                'description_ru' => 'Стартапы в области технологий путешествий (TravelTech).',
                'description_uz' => 'Sayohat texnologiyalari (TravelTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 15,
                'title_en' => 'PropTech',
                'title_ru' => 'Технологии недвижимости',
                'title_uz' => 'PropTech',
                'description_en' => 'Startups in property technologies (PropTech).',
                'description_ru' => 'Стартапы в области технологий недвижимости (PropTech).',
                'description_uz' => 'Ko‘chmas mulk texnologiyalari (PropTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 16,
                'title_en' => 'Logistics',
                'title_ru' => 'Логистика',
                'title_uz' => 'Logistika',
                'description_en' => 'Startups in logistics.',
                'description_ru' => 'Стартапы в области логистики.',
                'description_uz' => 'Logistika bo‘yicha startaplar.',
            ],
            [
                'id' => 17,
                'title_en' => 'Social Media',
                'title_ru' => 'Социальные сети и медиа технологии',
                'title_uz' => 'Ijtimoiy media',
                'description_en' => 'Startups in social networks and media technologies.',
                'description_ru' => 'Стартапы в области социальных сетей и медиа технологий.',
                'description_uz' => 'Ijtimoiy tarmoqlar va media texnologiyalari bo‘yicha startaplar.',
            ],
            [
                'id' => 18,
                'title_en' => 'Mobile Applications',
                'title_ru' => 'Мобильные приложения',
                'title_uz' => 'Mobil ilovalar',
                'description_en' => 'Startups in mobile applications.',
                'description_ru' => 'Стартапы в области мобильных приложений.',
                'description_uz' => 'Mobil ilovalar sohasidagi startaplar.',
            ],
            [
                'id' => 19,
                'title_en' => 'Wearables',
                'title_ru' => 'Носимые технологии',
                'title_uz' => 'Kiyiladigan texnologiyalar',
                'description_en' => 'Startups in wearables technologies.',
                'description_ru' => 'Стартапы в области носимых технологий.',
                'description_uz' => 'Kiyiladigan texnologiyalar (Wearables) bo‘yicha startaplar.',
            ],
            [
                'id' => 20,
                'title_en' => 'Robotics',
                'title_ru' => 'Робототехника',
                'title_uz' => 'Robototexnika',
                'description_en' => 'Startups in robotics.',
                'description_ru' => 'Стартапы в области робототехники.',
                'description_uz' => 'Robototexnika bo‘yicha startaplar.',
            ],
            [
                'id' => 21,
                'title_en' => 'Energy',
                'title_ru' => 'Энергетика',
                'title_uz' => 'Energiya',
                'description_en' => 'Startups in the energy sector.',
                'description_ru' => 'Стартапы в области энергетики.',
                'description_uz' => 'Energiya sohasidagi startaplar.',
            ],
            [
                'id' => 22,
                'title_en' => 'Smart Cities',
                'title_ru' => 'Умные города',
                'title_uz' => 'Aqlli shaharlar',
                'description_en' => 'Startups in smart city technologies.',
                'description_ru' => 'Стартапы в области технологий умных городов.',
                'description_uz' => 'Aqlli shahar texnologiyalari (Smart Cities) bo‘yicha startaplar.',
            ],
            [
                'id' => 23,
                'title_en' => 'Automotive',
                'title_ru' => 'Автомобильная промышленность',
                'title_uz' => 'Avtomobil sanoati',
                'description_en' => 'Startups in automotive technologies.',
                'description_ru' => 'Стартапы в области автомобильных технологий.',
                'description_uz' => 'Avtomobil texnologiyalari (Automotive) bo‘yicha startaplar.',
            ],
            [
                'id' => 24,
                'title_en' => 'MarTech',
                'title_ru' => 'Маркетинговые технологии',
                'title_uz' => 'MarTech',
                'description_en' => 'Startups in marketing technologies (MarTech).',
                'description_ru' => 'Стартапы в области маркетинговых технологий (MarTech).',
                'description_uz' => 'Marketing texnologiyalari (MarTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 25,
                'title_en' => 'AdTech',
                'title_ru' => 'Рекламные технологии',
                'title_uz' => 'AdTech',
                'description_en' => 'Startups in advertising technologies (AdTech).',
                'description_ru' => 'Стартапы в области рекламных технологий (AdTech).',
                'description_uz' => 'Reklama texnologiyalari (AdTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 26,
                'title_en' => 'LegalTech',
                'title_ru' => 'Юридические технологии',
                'title_uz' => 'LegalTech',
                'description_en' => 'Startups in legal technologies (LegalTech).',
                'description_ru' => 'Стартапы в области юридических технологий (LegalTech).',
                'description_uz' => 'Yuridik texnologiyalar (LegalTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 27,
                'title_en' => 'HRTech',
                'title_ru' => 'Технологии управления персоналом',
                'title_uz' => 'HRTech',
                'description_en' => 'Startups in human resources technologies (HRTech).',
                'description_ru' => 'Стартапы в области технологий управления персоналом (HRTech).',
                'description_uz' => 'Kadrlar boshqaruvi texnologiyalari (HRTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 28,
                'title_en' => 'Real Estate',
                'title_ru' => 'Недвижимость',
                'title_uz' => 'Ko‘chmas mulk',
                'description_en' => 'Startups in real estate.',
                'description_ru' => 'Стартапы в области недвижимости.',
                'description_uz' => 'Ko‘chmas mulk bo‘yicha startaplar.',
            ],
            [
                'id' => 29,
                'title_en' => 'SportsTech',
                'title_ru' => 'Спортивные технологии',
                'title_uz' => 'SportTech',
                'description_en' => 'Startups in sports technologies (SportsTech).',
                'description_ru' => 'Стартапы в области спортивных технологий (SportsTech).',
                'description_uz' => 'Sport texnologiyalari (SportsTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 30,
                'title_en' => 'RetailTech',
                'title_ru' => 'Технологии розничной торговли',
                'title_uz' => 'RetailTech',
                'description_en' => 'Startups in retail technologies (RetailTech).',
                'description_ru' => 'Стартапы в области технологий розничной торговли (RetailTech).',
                'description_uz' => 'Chakana savdo texnologiyalari (RetailTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 31,
                'title_en' => 'InsurTech',
                'title_ru' => 'Технологии страхования',
                'title_uz' => 'InsurTech',
                'description_en' => 'Startups in insurance technologies (InsurTech).',
                'description_ru' => 'Стартапы в области технологий страхования (InsurTech).',
                'description_uz' => 'Sug‘urta texnologiyalari (InsurTech) bo‘yicha startaplar.',
            ],
            [
                'id' => 32,
                'title_en' => 'Media and Entertainment',
                'title_ru' => 'Медиа и развлекательные технологии',
                'title_uz' => 'Media va Ko‘ngilochar',
                'description_en' => 'Media and entertainment technologies.',
                'description_ru' => 'Медиа и развлекательные технологии.',
                'description_uz' => 'Media va ko‘ngilochar texnologiyalar.',
            ],
            [
                'id' => 33,
                'title_en' => 'Telecommunications',
                'title_ru' => 'Телекоммуникации',
                'title_uz' => 'Telekom',
                'description_en' => 'Startups in telecommunications (Telecom) technologies.',
                'description_ru' => 'Стартапы в области телекоммуникационных технологий (Telecom).',
                'description_uz' => 'Telekommunikatsiyalar (Telecom) bo‘yicha startaplar.',
            ],
            [
                'id' => 34,
                'title_en' => 'Education',
                'title_ru' => 'Образование',
                'title_uz' => 'Ta’lim',
                'description_en' => 'Startups in the education sector.',
                'description_ru' => 'Стартапы в области образования.',
                'description_uz' => 'Ta’lim sohasidagi startaplar.',
            ],
            [
                'id' => 35,
                'title_en' => 'Healthcare',
                'title_ru' => 'Здравоохранение',
                'title_uz' => 'Sog‘liqni saqlash',
                'description_en' => 'Startups in the healthcare sector.',
                'description_ru' => 'Стартапы в области здравоохранения.',
                'description_uz' => 'Sog‘liqni saqlash sohasidagi startaplar.',
            ],
            [
                'id' => 36,
                'title_en' => 'Environmental',
                'title_ru' => 'Экологические технологии',
                'title_uz' => 'Atrof-muhit',
                'description_en' => 'Startups in environmental technologies (Environmental).',
                'description_ru' => 'Стартапы в области экологических технологий (Environmental).',
                'description_uz' => 'Atrof-muhit texnologiyalari (Environmental) bo‘yicha startaplar.',
            ],
            [
                'id' => 37,
                'title_en' => 'Manufacturing',
                'title_ru' => 'Производственные технологии',
                'title_uz' => 'Ishlab chiqarish',
                'description_en' => 'Startups in manufacturing technologies (Manufacturing).',
                'description_ru' => 'Стартапы в области производственных технологий (Manufacturing).',
                'description_uz' => 'Ishlab chiqarish texnologiyalari (Manufacturing) bo‘yicha startaplar.',
            ],
            [
                'id' => 38,
                'title_en' => 'Transportation',
                'title_ru' => 'Транспортные технологии',
                'title_uz' => 'Transport',
                'description_en' => 'Startups in transportation technologies (Transportation).',
                'description_ru' => 'Стартапы в области транспортных технологий (Transportation).',
                'description_uz' => 'Transport texnologiyalari (Transportation) bo‘yicha startaplar.',
            ],
            [
                'id' => 39,
                'title_en' => 'Supply Chain',
                'title_ru' => 'Технологии цепочки поставок',
                'title_uz' => 'Taminot zanjiri',
                'description_en' => 'Startups in supply chain technologies (Supply Chain).',
                'description_ru' => 'Стартапы в области технологий цепочки поставок (Supply Chain).',
                'description_uz' => 'Taminot zanjiri texnologiyalari (Supply Chain) bo‘yicha startaplar.',
            ],
            [
                'id' => 40,
                'title_en' => 'Virtual Reality',
                'title_ru' => 'Виртуальная реальность',
                'title_uz' => 'Virtual Haqiqat',
                'description_en' => 'Startups in virtual reality technologies (Virtual Reality).',
                'description_ru' => 'Стартапы в области технологий виртуальной реальности (Virtual Reality).',
                'description_uz' => 'Virtual haqiqat texnologiyalari (Virtual Reality).',
            ],
            [
                'id' => 41,
                'title_en' => 'Augmented Reality',
                'title_ru' => 'Дополненная реальность',
                'title_uz' => 'Qo‘shimcha Haqiqat',
                'description_en' => 'Startups in augmented reality technologies (Augmented Reality).',
                'description_ru' => 'Стартапы в области технологий дополненной реальности (Augmented Reality).',
                'description_uz' => 'Qo‘shimcha haqiqat texnologiyalari (Augmented Reality).',
            ],
            [
                'id' => 42,
                'title_en' => 'Fashion',
                'title_ru' => 'Мода',
                'title_uz' => 'Moda',
                'description_en' => 'Startups in fashion technologies (Fashion).',
                'description_ru' => 'Стартапы в области технологий моды (Fashion).',
                'description_uz' => 'Moda texnologiyalari (Fashion).',
            ],
            [
                'id' => 43,
                'title_en' => 'Art and Design',
                'title_ru' => 'Искусство и дизайн',
                'title_uz' => 'San’at va Dizayn',
                'description_en' => 'Startups in art and design.',
                'description_ru' => 'Стартапы в области искусства и дизайна.',
                'description_uz' => 'San’at va dizayn sohasidagi startaplar.',
            ],
            [
                'id' => 44,
                'title_en' => 'Nonprofit',
                'title_ru' => 'Некоммерческие технологии',
                'title_uz' => 'Notijorat',
                'description_en' => 'Technologies for nonprofit organizations.',
                'description_ru' => 'Технологии для некоммерческих организаций.',
                'description_uz' => 'Notijorat tashkilotlar uchun texnologiyalar (Nonprofit).',
            ],
            [
                'id' => 45,
                'title_en' => 'Social Impact',
                'title_ru' => 'Технологии социального воздействия',
                'title_uz' => 'Ijtimoiy ta’sir',
                'description_en' => 'Startups in social impact technologies (Social Impact).',
                'description_ru' => 'Стартапы в области технологий социального воздействия (Social Impact).',
                'description_uz' => 'Ijtimoiy ta’sir texnologiyalari (Social Impact).',
            ],
            [
                'id' => 46,
                'title_en' => 'PetTech',
                'title_ru' => 'Технологии для домашних животных',
                'title_uz' => 'PetTech',
                'description_en' => 'Startups in pet technologies (PetTech).',
                'description_ru' => 'Стартапы в области технологий для домашних животных (PetTech).',
                'description_uz' => 'Uy hayvonlari texnologiyalari (PetTech).',
            ],
            [
                'id' => 47,
                'title_en' => 'SpaceTech',
                'title_ru' => 'Космические технологии',
                'title_uz' => 'SpaceTech',
                'description_en' => 'Startups in space technologies (SpaceTech).',
                'description_ru' => 'Стартапы в области космических технологий (SpaceTech).',
                'description_uz' => 'Kosmik texnologiyalar (SpaceTech).',
            ],
            [
                'id' => 48,
                'title_en' => 'Financing',
                'title_ru' => 'Финансирование',
                'title_uz' => 'Moliyalash',
                'description_en' => 'Startups in financing technologies (Financing).',
                'description_ru' => 'Стартапы в области технологий финансирования (Financing).',
                'description_uz' => 'Moliyalash texnologiyalari (Financing).',
            ],
            [
                'id' => 49,
                'title_en' => 'Consulting',
                'title_ru' => 'Консалтинговые услуги',
                'title_uz' => 'Konsalting',
                'description_en' => 'Startups in consulting services.',
                'description_ru' => 'Стартапы в области консалтинговых услуг.',
                'description_uz' => 'Konsalting xizmatlari bo‘yicha startaplar.',
            ],
            [
                'id' => 50,
                'title_en' => 'Event Management',
                'title_ru' => 'Технологии управления мероприятиями',
                'title_uz' => 'Tadbirlarni boshqarish',
                'description_en' => 'Startups in event management technologies (Event Management).',
                'description_ru' => 'Стартапы в области технологий управления мероприятиями (Event Management).',
                'description_uz' => 'Tadbirlarni boshqarish texnologiyalari (Event Management).',
            ],
        ];
    }
}
